name: commute_calendar
description: "근태 관리 달력"

publish_to: 'DU-Company'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  bloc: ^8.1.2
  phosphor_flutter: ^2.1.0
  flutter_dotenv: ^5.1.0
  table_calendar: ^3.1.0
  equatable: ^2.0.5
  supabase_flutter: ^2.14.2
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  world_holidays: ^2.0.1
  intl: ^0.20.0
  go_router: ^14.0.0
  toastification: ^3.2.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - .env
    - .env_example
    - assets/fonts/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
